site_name: My Docs
site_name: Stairway to Salesforce
site_description: ETL Python Framework for Salesforce built on DLT
site_author: SFXD
repo_url: https://github.com/SFXD/stairway-to-salesforce
repo_name: SFXD/stairway-to-salesforce

theme:
  name: material
  palette:
    primary: indigo
    accent: light blue
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - content.code.copy

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Examples: examples.md
  - API Reference: api-reference.md
  - Testing: testing.md
  - Contributing: contributing.md

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search