[sources.salesforce_bulk2.credentials]
consumer_key = "< to define >"
consumer_secret = "< to define >"
domain = "< to define >.my"

[destination.postgres.credentials]
database = "< to define >" 
password = "< to define >" 
username = "< to define >" 
host = "< to define >" 
port = 5432
connect_timeout = 15
